# Generated by Django 3.0.6 on 2020-05-23 13:06

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_words',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='foodname',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10, null=True), max_length=220, null=True, size=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='foodweight',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10, null=True), max_length=220, null=True, size=20),
        ),
    ]
