# Generated by Django 3.0.6 on 2020-05-23 13:10

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200523_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='checkedfood',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10, null=True), max_length=220, null=True, size=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='checkweight',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10, null=True), max_length=220, null=True, size=20),
        ),
    ]
