# Generated by Django 3.0.6 on 2020-05-24 04:43

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200523_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kome',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10, null=True), max_length=220, null=True, size=20),
        ),
    ]
