# Generated by Django 3.0.6 on 2020-05-24 05:31

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_kome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='kome',
            new_name='checkedfood',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='foodname1',
        ),
        migrations.AddField(
            model_name='profile',
            name='checkweight',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10, null=True), max_length=220, null=True, size=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='foodname',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10, null=True), max_length=220, null=True, size=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='foodweight',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10, null=True), max_length=220, null=True, size=20),
        ),
    ]
