# Generated by Django 3.0.6 on 2020-05-24 13:21

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200524_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='checkryo',
            field=django_mysql.models.ListCharField(models.CharField(default='g', max_length=10, null=True), max_length=220, null=True, size=20),
        ),
    ]
