# Generated by Django 3.0.6 on 2020-06-07 05:28

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_checkryo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='checkedfood',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=10, null=True), max_length=220, null=True, size=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='checkryo',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, default='g', max_length=10, null=True), max_length=220, null=True, size=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='checkweight',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=10, null=True), max_length=220, null=True, size=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='foodname',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=10, null=True), max_length=220, null=True, size=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='foodweight',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=10, null=True), max_length=220, null=True, size=20),
        ),
    ]
