# Generated by Django 3.0.6 on 2020-06-07 06:10

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200607_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='checkryo',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, default='g', max_length=10, null=True), blank=True, max_length=231, null=True, size=21),
        ),
    ]
