# Generated by Django 3.0.6 on 2020-06-15 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200607_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='day',
            field=models.DateField(default=datetime.date(2020, 6, 15)),
        ),
    ]
