# Generated by Django 3.0.6 on 2020-06-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='day',
        ),
    ]
