# Generated by Django 3.0.6 on 2020-06-16 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_profile_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='day',
            field=models.DateField(default=datetime.date(2020, 6, 16)),
        ),
    ]
