# Generated by Django 3.0.6 on 2020-06-07 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('ingredient', django_mysql.models.ListCharField(models.CharField(max_length=10, null=True), max_length=220, null=True, size=20)),
                ('weight', django_mysql.models.ListCharField(models.CharField(max_length=10, null=True), max_length=220, null=True, size=20)),
                ('recipe', models.TextField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
