# Generated by Django 3.0.6 on 2020-06-07 10:46

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='hyojiweight',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10, null=True), max_length=220, null=True, size=20),
        ),
    ]
