# Generated by Django 3.0.6 on 2020-06-14 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20200614_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycalender',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mycalender',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe'),
        ),
        migrations.AlterField(
            model_name='mycalender',
            name='time',
            field=models.IntegerField(choices=[(1, '朝'), (2, '昼'), (3, '夜'), (4, '間食等')], null=True),
        ),
    ]
