# Generated by Django 3.0.6 on 2020-06-15 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20200614_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycalender',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe'),
        ),
    ]
